// AUTO-GENERATED - Core Convex React bindings
// DO NOT EDIT - Generated by convex-rescript-codegen

// ConvexReactClient for initializing the connection
module ConvexReactClient = {
  type t
  
  @module("convex/react") @new
  external make: string => t = "ConvexReactClient"
}

// ConvexProvider component
module ConvexProvider = {
  @react.component @module("convex/react")
  external make: (~client: ConvexReactClient.t, ~children: React.element) => React.element = "ConvexProvider"
}

// Core hooks - these are used by generated bindings
@module("convex/react")
external useMutation: 'functionReference => 'mutationFunction = "useMutation"

@module("convex/react")
external useQuery: ('functionReference, 'args) => option<'result> = "useQuery"

@module("convex/react")
external useAction: 'functionReference => 'actionFunction = "useAction"

// Authenticated versions
module Authenticated = {
  @module("convex/react")
  external useMutation: ('functionReference, 'identity) => 'mutationFunction = "useMutation"
  
  @module("convex/react")
  external useQuery: ('functionReference, 'args, 'identity) => option<'result> = "useQuery"
  
  @module("convex/react")
  external useAction: ('functionReference, 'identity) => 'actionFunction = "useAction"
}

// Convex client hooks
module Client = {
  @module("convex/react")
  external useConvex: unit => 'convexClient = "useConvex"
  
  @module("convex/react")
  external useConvexAuth: unit => 'authState = "useConvexAuth"
}

// Pagination support
type paginationResult<'a> = {
  page: array<'a>,
  isDone: bool,
  continueCursor: string,
}

@module("convex/react")
external usePaginatedQuery: ('functionReference, 'args, 'options) => paginationResult<'result> = "usePaginatedQuery"
