import { $ } from "bun";
import { parseConvexFunctions } from "./parser";
import { parseConvexSchema } from "./schema-parser";
import { generateModuleCode } from "./templates";
import type { GeneratorOptions, GeneratorResult, TableSchema } from "./types";

export async function generateBindings(
  inputPath: string, 
  outputPath: string,
  options: GeneratorOptions = {}
): Promise<GeneratorResult> {
  const { verbose = false, parseSchema = true } = options;
  
  // Parse schema if it exists
  let schema: Map<string, TableSchema> = new Map();
  if (parseSchema) {
    const schemaPath = `${inputPath}/schema.ts`;
    try {
      const schemaFile = Bun.file(schemaPath);
      if (await schemaFile.exists()) {
        schema = await parseConvexSchema(schemaPath);
        if (verbose) {
          console.log(`  Parsed schema with ${schema.size} tables`);
        }
      }
    } catch (error) {
      if (verbose) {
        console.warn(`  Warning: Could not parse schema: ${error}`);
      }
    }
  }
  
  // Parse all Convex functions
  const functions = await parseConvexFunctions(inputPath);
  
  // Group functions by module
  const modules = new Map<string, typeof functions>();
  for (const fn of functions) {
    if (!modules.has(fn.module)) {
      modules.set(fn.module, []);
    }
    modules.get(fn.module)!.push(fn);
  }
  
  // Create output directory using Bun's $
  await $`mkdir -p ${outputPath}`.quiet();
  
  // Generate bindings for each module
  const generatedFiles: string[] = [];
  
  for (const [moduleName, moduleFunctions] of modules) {
    // Get the corresponding table schema if it exists
    const tableSchema = schema.get(`${moduleName}s`) || schema.get(moduleName);
    
    const code = generateModuleCode(moduleName, moduleFunctions, tableSchema);
    const outputFile = `${outputPath}/Convex_${moduleName}.res`;
    
    // Write file using Bun.write
    await Bun.write(outputFile, code);
    generatedFiles.push(outputFile);
    
    if (verbose) {
      console.log(`  Generated: ${outputFile}`);
    }
  }
  
  // Generate index file that re-exports all modules
  const indexCode = generateIndexCode(Array.from(modules.keys()));
  const indexFile = `${outputPath}/ConvexGenerated.res`;
  await Bun.write(indexFile, indexCode);
  generatedFiles.push(indexFile);
  
  // Also generate a types file for shared types and schema
  const typesCode = generateTypesCode(schema);
  const typesFile = `${outputPath}/ConvexTypes.res`;
  await Bun.write(typesFile, typesCode);
  generatedFiles.push(typesFile);
  
  // Generate the core ConvexBindings file
  const bindingsCode = generateConvexBindings();
  const bindingsFile = `${outputPath}/../ConvexBindings.res`;
  await Bun.write(bindingsFile, bindingsCode);
  generatedFiles.push(bindingsFile);
  
  return {
    functionsCount: functions.length,
    modulesCount: modules.size,
    generatedFiles,
    warnings: [],
  };
}

function generateIndexCode(modules: string[]): string {
  const header = `// AUTO-GENERATED by convex-rescript-codegen
// DO NOT EDIT - This file re-exports all generated Convex modules

`;
  
  const moduleExports = modules
    .map(name => {
      const capitalized = name.charAt(0).toUpperCase() + name.slice(1);
      return `module ${capitalized} = Convex_${name}`;
    })
    .join("\n");
  
  return header + moduleExports + "\n";
}

function generateTypesCode(schema: Map<string, TableSchema>): string {
  let code = `// AUTO-GENERATED - Shared types for Convex bindings
// DO NOT EDIT

// ID types for each table
`;

  // Generate ID types for each table
  for (const tableName of schema.keys()) {
    code += `type ${tableName}Id = string\n`;
  }

  code += `
// API types from Convex
@module("../../convex/_generated/api")
external api: 'api = "api"

@module("../../convex/_generated/api")
external internal: 'api = "internal"



`;

  // Generate type definitions for each table
  if (schema.size > 0) {
    code += "// Table document types\n";
    
    for (const [tableName, tableSchema] of schema) {
      code += generateTableType(tableName, tableSchema);
    }
  }
  
  return code;
}

// ReScript reserved keywords that need escaping
const RESCRIPT_KEYWORDS = new Set([
  'and', 'as', 'assert', 'begin', 'class', 'constraint', 'do', 'done',
  'downto', 'else', 'end', 'exception', 'external', 'false', 'for',
  'fun', 'function', 'functor', 'if', 'in', 'include', 'inherit',
  'initializer', 'lazy', 'let', 'match', 'method', 'module', 'mutable',
  'new', 'nonrec', 'object', 'of', 'open', 'or', 'private', 'rec',
  'sig', 'struct', 'then', 'to', 'true', 'try', 'type', 'val',
  'virtual', 'when', 'while', 'with', 'mod', 'land', 'lor', 'lxor',
  'lsl', 'lsr', 'asr', 'switch', 'catch', 'await', 'async'
]);

// Escape ReScript reserved keywords
function escapeFieldName(name: string): string {
  if (RESCRIPT_KEYWORDS.has(name)) {
    return `${name}_`;
  }
  return name;
}

// Generate field with @as decorator if needed
function generateRecordField(name: string, type: string): string {
  const escaped = escapeFieldName(name);
  if (escaped !== name) {
    return `  @as("${name}") ${escaped}: ${type}`;
  }
  return `  ${name}: ${type}`;
}

function generateTableType(tableName: string, schema: TableSchema): string {
  let code = `\n// Document type for ${tableName} table\n`;
  
  // Generate the document type name
  const typeName = `${tableName}Doc`;
  
  code += `type ${typeName} = {\n`;
  
  // Add system fields
  code += `  @as("_id") id: ${tableName}Id,\n`;
  code += `  @as("_creationTime") creationTime: float,\n`;
  
  // Add user-defined fields
  for (const [fieldName, fieldSchema] of Object.entries(schema.fields)) {
    let fieldType = '';
    
    if (fieldSchema.type === "optional") {
      fieldType = fieldSchema.rescriptType;
    } else if (fieldSchema.type === "union" && fieldSchema.literals) {
      // Create a polymorphic variant type for unions
      // Escape reserved keywords in variant tags
      fieldType = `[${fieldSchema.literals.map(l => {
        if (RESCRIPT_KEYWORDS.has(l)) {
          return `| #"${l}"`;  // Use string syntax for reserved keywords
        }
        return `| #${l}`;
      }).join(' ')}]`;
    } else {
      fieldType = fieldSchema.rescriptType;
    }
    
    // Use the helper to generate field with proper escaping
    const field = generateRecordField(fieldName, fieldType);
    code += field + ',\n';
  }
  
  code += `}\n`;
  
  return code;
}

function generateConvexBindings(): string {
  return `// AUTO-GENERATED - Core Convex React bindings
// DO NOT EDIT - Generated by convex-rescript-codegen

// ConvexReactClient for initializing the connection
module ConvexReactClient = {
  type t
  
  @module("convex/react") @new
  external make: string => t = "ConvexReactClient"
}

// ConvexProvider component
module ConvexProvider = {
  @react.component @module("convex/react")
  external make: (~client: ConvexReactClient.t, ~children: React.element) => React.element = "ConvexProvider"
}

// Core hooks - these are used by generated bindings
@module("convex/react")
external useMutation: 'functionReference => 'mutationFunction = "useMutation"

@module("convex/react")
external useQuery: ('functionReference, 'args) => option<'result> = "useQuery"

@module("convex/react")
external useAction: 'functionReference => 'actionFunction = "useAction"

// Authenticated versions
module Authenticated = {
  @module("convex/react")
  external useMutation: ('functionReference, 'identity) => 'mutationFunction = "useMutation"
  
  @module("convex/react")
  external useQuery: ('functionReference, 'args, 'identity) => option<'result> = "useQuery"
  
  @module("convex/react")
  external useAction: ('functionReference, 'identity) => 'actionFunction = "useAction"
}

// Convex client hooks
module Client = {
  @module("convex/react")
  external useConvex: unit => 'convexClient = "useConvex"
  
  @module("convex/react")
  external useConvexAuth: unit => 'authState = "useConvexAuth"
}

// Pagination support
type paginationResult<'a> = {
  page: array<'a>,
  isDone: bool,
  continueCursor: string,
}

@module("convex/react")
external usePaginatedQuery: ('functionReference, 'args, 'options) => paginationResult<'result> = "usePaginatedQuery"
`;
}