import type { ConvexFunction, TableSchema } from "./types";

// ReScript reserved keywords that need escaping
const RESCRIPT_KEYWORDS = new Set([
  'and', 'as', 'assert', 'begin', 'class', 'constraint', 'do', 'done',
  'downto', 'else', 'end', 'exception', 'external', 'false', 'for',
  'fun', 'function', 'functor', 'if', 'in', 'include', 'inherit',
  'initializer', 'lazy', 'let', 'match', 'method', 'module', 'mutable',
  'new', 'nonrec', 'object', 'of', 'open', 'or', 'private', 'rec',
  'sig', 'struct', 'then', 'to', 'true', 'try', 'type', 'val',
  'virtual', 'when', 'while', 'with', 'mod', 'land', 'lor', 'lxor',
  'lsl', 'lsr', 'asr', 'switch', 'catch', 'await', 'async'
]);

// Escape ReScript reserved keywords
function escapeFieldName(name: string): string {
  if (RESCRIPT_KEYWORDS.has(name)) {
    return `${name}_`;
  }
  return name;
}

// Generate field with @as decorator if needed
function generateRecordField(name: string, type: string): string {
  const escaped = escapeFieldName(name);
  if (escaped !== name) {
    return `  @as("${name}") ${escaped}: ${type}`;
  }
  return `  ${name}: ${type}`;
}

export function generateModuleCode(
  moduleName: string, 
  functions: ConvexFunction[], 
  tableSchema?: TableSchema
): string {
  const header = `// AUTO-GENERATED by convex-rescript-codegen
// DO NOT EDIT - Generated from convex/${moduleName}.ts
// Run \`bun run codegen\` to regenerate

open ConvexTypes

`;

  const functionModules = functions.map(fn => generateFunctionModule(moduleName, fn, tableSchema)).join("\n");
  
  return header + functionModules;
}

function generateFunctionModule(moduleName: string, fn: ConvexFunction, tableSchema?: TableSchema): string {
  const capitalizedType = fn.type.charAt(0).toUpperCase() + fn.type.slice(1);
  const modulePrefix = fn.isInternal ? "Internal" : "";
  const moduleName_ = `${modulePrefix}${capitalizedType}_${fn.name}`;
  
  if (fn.type === "query") {
    return generateQueryModule(moduleName_, moduleName, fn, tableSchema);
  } else if (fn.type === "mutation") {
    return generateMutationModule(moduleName_, moduleName, fn, tableSchema);
  } else if (fn.type === "action") {
    return generateActionModule(moduleName_, moduleName, fn, tableSchema);
  }
  
  return "";
}

function generateQueryModule(moduleName_: string, moduleName: string, fn: ConvexFunction, tableSchema?: TableSchema): string {
  const hasArgs = Object.keys(fn.args).length > 0;
  const apiPath = fn.isInternal ? "internal" : "api";
  
  // Determine output type based on function name and schema
  let outputType = fn.returnType || "JSON.t";
  
  // If we have a table schema, try to infer the return type
  if (tableSchema) {
    // The table name is already plural (agents, agentMessages, etc.)
    const tableName = moduleName.endsWith('s') ? moduleName : `${moduleName}s`;
    
    // Common query patterns
    if (fn.name === "list" || fn.name === "getAll") {
      outputType = `array<${tableName}Doc>`;
    } else if (fn.name === "getById" || fn.name === "get") {
      outputType = `option<${tableName}Doc>`;
    } else if (fn.name === "getByStatus" || fn.name.startsWith("getBy")) {
      outputType = `array<${tableName}Doc>`;
    }
  }
  
  if (!hasArgs) {
    return `module ${moduleName_} = {
  type output = ${outputType}
  
  @module("convex/react")
  external useQuery: ('api, unit) => option<output> = "useQuery"
  
  let use = () => {
    useQuery(${apiPath}["${moduleName}"]["${fn.name}"], ())
  }
}
`;
  }
  
  // Generate input type from args
  const inputFields = Object.entries(fn.args)
    .map(([name, type]) => generateRecordField(name, type) + ",")
    .join("\n");
  
  // Check if any args are optional - for now, treat all queries the same
  // This keeps it simple and avoids complexity
  
  return `module ${moduleName_} = {
  type input = {
${inputFields}
  }
  type output = ${outputType}
  
  @module("convex/react")
  external useQuery: ('api, input) => option<output> = "useQuery"
  
  let use = (${Object.keys(fn.args).map(name => `~${escapeFieldName(name)}`).join(", ")}) => {
    useQuery(${apiPath}["${moduleName}"]["${fn.name}"], {
      ${Object.keys(fn.args).map(name => {
        const escaped = escapeFieldName(name);
        return escaped === name ? `${name}: ${name}` : `${name}: ${escaped}`;
      }).join(",\n      ")}
    })
  }
}
`;
}

function generateMutationModule(moduleName_: string, moduleName: string, fn: ConvexFunction, tableSchema?: TableSchema): string {
  const hasArgs = Object.keys(fn.args).length > 0;
  const apiPath = fn.isInternal ? "internal" : "api";
  
  // Determine output type
  let outputType = fn.returnType || "JSON.t";
  
  // Common mutation patterns
  if (tableSchema) {
    const tableName = moduleName.endsWith('s') ? moduleName : `${moduleName}s`;
    
    if (fn.name === "create" || fn.name === "insert") {
      outputType = `${tableName}Id`;
    } else if (fn.name === "update" || fn.name === "updateStatus" || fn.name === "remove" || fn.name === "delete") {
      outputType = "unit";
    }
  } else {
    // No table schema for this module, use generic patterns
    if (fn.name === "send" || fn.name === "create" || fn.name === "insert") {
      // For messages.send, we return a message ID
      outputType = "string";
    } else if (fn.name === "update" || fn.name === "remove" || fn.name === "delete") {
      outputType = "unit";
    }
  }
  
  if (!hasArgs) {
    return `module ${moduleName_} = {
  type t = unit => promise<${outputType}>
  
  @module("convex/react")
  external useMutation: 'api => t = "useMutation"
  
  let use = () => {
    useMutation(${apiPath}["${moduleName}"]["${fn.name}"])
  }
}
`;
  }
  
  // Generate input type from args
  const inputFields = Object.entries(fn.args)
    .map(([name, type]) => generateRecordField(name, type) + ",")
    .join("\n");
  
  return `module ${moduleName_} = {
  type input = {
${inputFields}
  }
  type t = input => promise<${outputType}>
  
  @module("convex/react")
  external useMutation: 'api => t = "useMutation"
  
  let use = () => {
    useMutation(${apiPath}["${moduleName}"]["${fn.name}"])
  }
}
`;
}

function generateActionModule(moduleName_: string, moduleName: string, fn: ConvexFunction, tableSchema?: TableSchema): string {
  const hasArgs = Object.keys(fn.args).length > 0;
  const apiPath = fn.isInternal ? "internal" : "api";
  
  if (!hasArgs) {
    return `module ${moduleName_} = {
  type t = unit => promise<JSON.t>
  
  @module("convex/react")
  external useAction: 'api => t = "useAction"
  
  let use = () => {
    useAction(${apiPath}["${moduleName}"]["${fn.name}"])
  }
}
`;
  }
  
  // Generate input type from args
  const inputFields = Object.entries(fn.args)
    .map(([name, type]) => generateRecordField(name, type) + ",")
    .join("\n");
  
  return `module ${moduleName_} = {
  type input = {
${inputFields}
  }
  type t = input => promise<JSON.t>
  
  @module("convex/react")
  external useAction: 'api => t = "useAction"
  
  let use = () => {
    useAction(${apiPath}["${moduleName}"]["${fn.name}"])
  }
}
  type t = input => promise<${outputType}>
  
  @module("convex/react")
  external useAction: 'api => t = "useAction"
  
  let use = () => {
    useAction(${apiPath}["${moduleName}"]["${fn.name}"])
  }
}
`;
}