// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as ShadcnButton from "./ui/ShadcnButton.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function AgentCard(props) {
  let onExecute = props.onExecute;
  let agent = props.agent;
  let match = React.useState(() => false);
  let setIsLoading = match[1];
  let isLoading = match[0];
  let handleClick = async param => {
    setIsLoading(param => true);
    try {
      await onExecute(agent.id);
      return setIsLoading(param => false);
    } catch (raw_err) {
      let err = Primitive_exceptions.internalToException(raw_err);
      if (err.RE_EXN_ID === Stdlib_Exn.$$Error) {
        console.error("Failed to execute agent:", err._1);
        return setIsLoading(param => false);
      }
      throw err;
    }
  };
  let match$1 = agent.status;
  let statusColor;
  if (typeof match$1 !== "object") {
    switch (match$1) {
      case "Idle" :
        statusColor = "bg-gray-100";
        break;
      case "Processing" :
        statusColor = "bg-blue-100";
        break;
      case "Completed" :
        statusColor = "bg-green-100";
        break;
    }
  } else {
    statusColor = "bg-red-100";
  }
  let msg = agent.status;
  let tmp;
  if (typeof msg !== "object") {
    switch (msg) {
      case "Idle" :
        tmp = "Idle";
        break;
      case "Processing" :
        tmp = "Processing";
        break;
      case "Completed" :
        tmp = "Completed";
        break;
    }
  } else {
    tmp = `Failed: ` + msg._0;
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h3", {
            children: agent.name,
            className: "text-lg font-semibold"
          }),
          JsxRuntime.jsx("span", {
            children: tmp,
            className: `px-2 py-1 rounded-full text-xs ` + statusColor
          })
        ],
        className: "flex justify-between items-start mb-3"
      }),
      JsxRuntime.jsx("p", {
        children: agent.description,
        className: "text-sm text-gray-600 mb-4"
      }),
      JsxRuntime.jsx("div", {
        children: agent.capabilities.map(cap => {
          let capName;
          switch (cap) {
            case "Chat" :
              capName = "Chat";
              break;
            case "ImageGeneration" :
              capName = "Image";
              break;
            case "CodeExecution" :
              capName = "Code";
              break;
            case "DataAnalysis" :
              capName = "Data";
              break;
            case "WebSearch" :
              capName = "Search";
              break;
          }
          return JsxRuntime.jsx("span", {
            children: capName,
            className: "px-2 py-1 bg-gray-100 rounded text-xs"
          }, capName);
        }),
        className: "flex flex-wrap gap-1 mb-4"
      }),
      JsxRuntime.jsx(ShadcnButton.Button.make, {
        children: isLoading ? "Executing..." : "Execute Agent",
        variant: "default",
        size: "sm",
        disabled: isLoading || agent.status === "Processing",
        onClick: handleClick
      })
    ],
    className: "agent-card p-4 border rounded-lg shadow-sm hover:shadow-md transition-shadow"
  });
}

let make = AgentCard;

export {
  make,
}
/* react Not a pure module */
