// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as AgentConvex from "../bindings/AgentConvex.res.mjs";
import * as ShadcnButton from "./ui/ShadcnButton.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function AgentList(props) {
  let agents = AgentConvex.Query_listAgents.use();
  let createAgent = AgentConvex.Mutation_createAgent.use();
  AgentConvex.Mutation_updateAgentStatus.use();
  let executeAgent = AgentConvex.Mutation_executeAgent.use();
  let removeAgent = AgentConvex.Mutation_removeAgent.use();
  let match = React.useState(() => false);
  let setShowCreateForm = match[1];
  let match$1 = React.useState(() => "");
  let setNewAgentName = match$1[1];
  let newAgentName = match$1[0];
  let match$2 = React.useState(() => "");
  let setNewAgentDescription = match$2[1];
  let newAgentDescription = match$2[0];
  let match$3 = React.useState(() => "assistant");
  let setNewAgentRole = match$3[1];
  let newAgentRole = match$3[0];
  let handleCreateAgent = async param => {
    if (newAgentName === "" || newAgentDescription === "") {
      return;
    }
    try {
      await createAgent({
        name: newAgentName,
        description: newAgentDescription,
        role: newAgentRole,
        capabilities: [
          "chat",
          "analyze"
        ]
      });
      setShowCreateForm(param => false);
      setNewAgentName(param => "");
      setNewAgentDescription(param => "");
      return setNewAgentRole(param => "assistant");
    } catch (raw_err) {
      let err = Primitive_exceptions.internalToException(raw_err);
      if (err.RE_EXN_ID === Stdlib_Exn.$$Error) {
        console.error("Failed to create agent:", err._1);
        return;
      }
      throw err;
    }
  };
  let handleExecuteAgent = async agentId => {
    try {
      await executeAgent({
        agentId: agentId,
        task: "process",
        parameters: Object.fromEntries([[
            "action",
            "analyze"
          ]])
      });
      console.log(`Agent ` + agentId + ` execution started`);
      return;
    } catch (raw_err) {
      let err = Primitive_exceptions.internalToException(raw_err);
      if (err.RE_EXN_ID === Stdlib_Exn.$$Error) {
        console.error("Failed to execute agent:", err._1);
        return;
      }
      throw err;
    }
  };
  let handleRemoveAgent = async agentId => {
    try {
      await removeAgent({
        agentId: agentId
      });
      console.log(`Agent ` + agentId + ` removed`);
      return;
    } catch (raw_err) {
      let err = Primitive_exceptions.internalToException(raw_err);
      if (err.RE_EXN_ID === Stdlib_Exn.$$Error) {
        console.error("Failed to remove agent:", err._1);
        return;
      }
      throw err;
    }
  };
  let stats;
  if (agents !== undefined) {
    let total = agents.length;
    let idle = agents.filter(a => a.status === "idle").length;
    let processing = agents.filter(a => a.status === "processing").length;
    let completed = agents.filter(a => a.status === "completed").length;
    let failed = agents.filter(a => a.status === "failed").length;
    stats = {
      total: total,
      idle: idle,
      processing: processing,
      completed: completed,
      failed: failed
    };
  } else {
    stats = {
      total: 0,
      idle: 0,
      processing: 0,
      completed: 0,
      failed: 0
    };
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("h3", {
                children: "Total Agents",
                className: "text-sm font-medium text-gray-500"
              }),
              JsxRuntime.jsx("p", {
                children: stats.total,
                className: "text-2xl font-semibold text-gray-900"
              })
            ],
            className: "bg-white rounded-lg shadow p-4"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("h3", {
                children: "Idle",
                className: "text-sm font-medium text-gray-500"
              }),
              JsxRuntime.jsx("p", {
                children: stats.idle,
                className: "text-2xl font-semibold text-gray-600"
              })
            ],
            className: "bg-white rounded-lg shadow p-4"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("h3", {
                children: "Processing",
                className: "text-sm font-medium text-gray-500"
              }),
              JsxRuntime.jsx("p", {
                children: stats.processing,
                className: "text-2xl font-semibold text-blue-600"
              })
            ],
            className: "bg-white rounded-lg shadow p-4"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("h3", {
                children: "Completed",
                className: "text-sm font-medium text-gray-500"
              }),
              JsxRuntime.jsx("p", {
                children: stats.completed,
                className: "text-2xl font-semibold text-green-600"
              })
            ],
            className: "bg-white rounded-lg shadow p-4"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("h3", {
                children: "Failed",
                className: "text-sm font-medium text-gray-500"
              }),
              JsxRuntime.jsx("p", {
                children: stats.failed,
                className: "text-2xl font-semibold text-red-600"
              })
            ],
            className: "bg-white rounded-lg shadow p-4"
          })
        ],
        className: "grid grid-cols-1 md:grid-cols-5 gap-4 mb-6"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("h2", {
                children: "Agents",
                className: "text-lg font-semibold text-gray-900"
              }),
              JsxRuntime.jsx(ShadcnButton.Button.make, {
                children: "Create Agent",
                variant: "default",
                size: "sm",
                onClick: async param => setShowCreateForm(param => true)
              })
            ],
            className: "px-6 py-4 border-b flex justify-between items-center"
          }),
          JsxRuntime.jsx("div", {
            children: agents !== undefined ? (
                agents.length !== 0 ? JsxRuntime.jsx("div", {
                    children: agents.map(agent => {
                      let match = agent.status;
                      let statusColor;
                      switch (match) {
                        case "completed" :
                          statusColor = "bg-green-100 text-green-700";
                          break;
                        case "failed" :
                          statusColor = "bg-red-100 text-red-700";
                          break;
                        case "processing" :
                          statusColor = "bg-blue-100 text-blue-700";
                          break;
                        default:
                          statusColor = "bg-gray-100 text-gray-700";
                      }
                      return JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("h3", {
                                children: agent.name,
                                className: "font-semibold text-gray-900"
                              }),
                              JsxRuntime.jsx("span", {
                                children: agent.status,
                                className: `px-2 py-1 rounded text-xs ` + statusColor
                              })
                            ],
                            className: "flex justify-between items-start mb-2"
                          }),
                          JsxRuntime.jsx("p", {
                            children: agent.description,
                            className: "text-sm text-gray-600 mb-3"
                          }),
                          JsxRuntime.jsx("div", {
                            children: agent.capabilities.map(cap => JsxRuntime.jsx("span", {
                              children: cap,
                              className: "px-2 py-1 bg-gray-100 rounded text-xs"
                            }, cap)),
                            className: "flex gap-1 mb-3"
                          }),
                          JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx(ShadcnButton.Button.make, {
                                children: "Execute",
                                variant: "default",
                                size: "sm",
                                disabled: agent.status === "processing",
                                onClick: async param => await handleExecuteAgent(agent._id)
                              }),
                              JsxRuntime.jsx(ShadcnButton.Button.make, {
                                children: "Remove",
                                variant: "destructive",
                                size: "sm",
                                onClick: async param => await handleRemoveAgent(agent._id)
                              })
                            ],
                            className: "flex gap-2"
                          })
                        ],
                        className: "border rounded-lg p-4"
                      }, agent._id);
                    }),
                    className: "grid gap-4 md:grid-cols-2 lg:grid-cols-3"
                  }) : JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsx("p", {
                      children: "No agents created yet. Click 'Create Agent' to get started.",
                      className: "text-gray-500"
                    }),
                    className: "text-center py-8"
                  })
              ) : JsxRuntime.jsx("div", {
                children: JsxRuntime.jsx("p", {
                  children: "Loading agents...",
                  className: "text-gray-500"
                }),
                className: "text-center py-8"
              }),
            className: "p-6"
          })
        ],
        className: "bg-white rounded-lg shadow"
      }),
      match[0] ? JsxRuntime.jsx("div", {
          children: JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("h2", {
                children: "Create New Agent",
                className: "text-xl font-semibold mb-4"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("label", {
                        children: "Name",
                        className: "block text-sm font-medium text-gray-700 mb-1"
                      }),
                      JsxRuntime.jsx("input", {
                        className: "w-full px-3 py-2 border border-gray-300 rounded-md",
                        placeholder: "Agent name",
                        type: "text",
                        value: newAgentName,
                        onChange: e => setNewAgentName(param => e.target.value)
                      })
                    ]
                  }),
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("label", {
                        children: "Description",
                        className: "block text-sm font-medium text-gray-700 mb-1"
                      }),
                      JsxRuntime.jsx("textarea", {
                        className: "w-full px-3 py-2 border border-gray-300 rounded-md",
                        placeholder: "What does this agent do?",
                        rows: 3,
                        value: newAgentDescription,
                        onChange: e => setNewAgentDescription(param => e.target.value)
                      })
                    ]
                  }),
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("label", {
                        children: "Role",
                        className: "block text-sm font-medium text-gray-700 mb-1"
                      }),
                      JsxRuntime.jsxs("select", {
                        children: [
                          JsxRuntime.jsx("option", {
                            children: "Assistant",
                            value: "assistant"
                          }),
                          JsxRuntime.jsx("option", {
                            children: "Analyzer",
                            value: "analyzer"
                          }),
                          JsxRuntime.jsx("option", {
                            children: "Processor",
                            value: "processor"
                          })
                        ],
                        className: "w-full px-3 py-2 border border-gray-300 rounded-md",
                        value: newAgentRole,
                        onChange: e => setNewAgentRole(param => e.target.value)
                      })
                    ]
                  })
                ],
                className: "space-y-4"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx(ShadcnButton.Button.make, {
                    children: "Cancel",
                    variant: "outline",
                    onClick: async param => setShowCreateForm(param => false)
                  }),
                  JsxRuntime.jsx(ShadcnButton.Button.make, {
                    children: "Create",
                    variant: "default",
                    onClick: handleCreateAgent
                  })
                ],
                className: "flex justify-end gap-2 mt-6"
              })
            ],
            className: "bg-white rounded-lg p-6 w-full max-w-md"
          }),
          className: "fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"
        }) : null
    ]
  });
}

let make = AgentList;

export {
  make,
}
/* react Not a pure module */
