// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as Convex_rooms from "../bindings/generated/Convex_rooms.res.mjs";
import * as Convex_messages from "../bindings/generated/Convex_messages.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function ChatRoom(props) {
  let userId = props.userId;
  let roomId = props.roomId;
  let room = Convex_rooms.Query_getById.use(roomId);
  let messagesRaw = Convex_messages.Query_getByRoom.use(roomId, 50);
  let members = Convex_rooms.Query_getMembers.use(roomId);
  let sendMessage = Convex_messages.Mutation_send.use();
  let match = React.useState(() => "");
  let setMessageText = match[1];
  let messageText = match[0];
  let handleSendMessage = async param => {
    if (messageText.trim() === "") {
      return;
    }
    try {
      await sendMessage({
        roomId: roomId,
        userId: userId,
        content: messageText,
        type: "text"
      });
      return setMessageText(param => "");
    } catch (raw_err) {
      let err = Primitive_exceptions.internalToException(raw_err);
      if (err.RE_EXN_ID === Stdlib_Exn.$$Error) {
        console.error("Failed to send message:", err._1);
        return;
      }
      throw err;
    }
  };
  let tmp;
  if (room !== undefined) {
    let roomData = Primitive_option.valFromOption(room);
    if (roomData !== undefined) {
      let desc = roomData.description;
      let match$1 = roomData.type;
      tmp = JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h2", {
            children: roomData.name,
            className: "text-xl font-semibold"
          }),
          desc !== undefined ? JsxRuntime.jsx("p", {
              children: desc,
              className: "text-gray-600 text-sm"
            }) : null,
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("span", {
                children: `Type: ` + (
                  match$1 === "private" ? "Private" : (
                      match$1 === "direct" ? "Direct" : "Public"
                    )
                ),
                className: "text-xs text-gray-500"
              }),
              members !== undefined ? JsxRuntime.jsx("span", {
                  children: `• ` + members.length.toString() + ` members`,
                  className: "text-xs text-gray-500"
                }) : null
            ],
            className: "flex items-center gap-2 mt-2"
          })
        ]
      });
    } else {
      tmp = JsxRuntime.jsx("div", {
        children: "Room not found",
        className: "text-red-500"
      });
    }
  } else {
    tmp = JsxRuntime.jsx("div", {
      children: "Loading room...",
      className: "text-gray-500"
    });
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: tmp,
        className: "bg-white border-b px-6 py-4"
      }),
      JsxRuntime.jsx("div", {
        children: messagesRaw !== undefined ? (
            messagesRaw.length === 0 ? JsxRuntime.jsx("div", {
                children: "No messages yet. Start the conversation!",
                className: "text-center text-gray-500 mt-8"
              }) : JsxRuntime.jsx("div", {
                children: messagesRaw.map(msg => {
                  let isOwnMessage = msg.userId === userId;
                  let user = msg.user;
                  return JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsxs("div", {
                      children: [
                        user !== undefined && !isOwnMessage ? JsxRuntime.jsx("div", {
                            children: user.name,
                            className: "text-xs font-semibold mb-1"
                          }) : null,
                        JsxRuntime.jsx("div", {
                          children: msg.content
                        }),
                        JsxRuntime.jsx("div", {
                          children: new Date(msg.createdAt).toLocaleTimeString(),
                          className: `text-xs mt-1 ` + (
                            isOwnMessage ? "text-blue-100" : "text-gray-500"
                          )
                        })
                      ],
                      className: `max-w-xs lg:max-w-md px-4 py-2 rounded-lg ` + (
                        isOwnMessage ? "bg-blue-500 text-white" : "bg-gray-200 text-gray-800"
                      )
                    }),
                    className: `flex ` + (
                      isOwnMessage ? "justify-end" : "justify-start"
                    )
                  }, msg._id);
                }),
                className: "space-y-4"
              })
          ) : JsxRuntime.jsx("div", {
            children: "Loading messages...",
            className: "text-center text-gray-500 mt-8"
          }),
        className: "flex-1 overflow-y-auto px-6 py-4"
      }),
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("input", {
              className: "flex-1 px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500",
              placeholder: "Type a message...",
              type: "text",
              value: messageText,
              onKeyDown: e => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  handleSendMessage();
                  return;
                }
              },
              onChange: e => {
                let target = e.target;
                let value = target.value;
                setMessageText(param => value);
              }
            }),
            JsxRuntime.jsx("button", {
              children: "Send",
              className: "px-6 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed",
              disabled: messageText.trim() === "",
              onClick: param => {
                handleSendMessage();
              }
            })
          ],
          className: "flex gap-2"
        }),
        className: "bg-white border-t px-6 py-4"
      })
    ],
    className: "flex flex-col h-screen bg-gray-50"
  });
}

let make = ChatRoom;

export {
  make,
}
/* react Not a pure module */
