// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ChatRoom from "./components/ChatRoom.res.mjs";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as Convex_rooms from "./bindings/generated/Convex_rooms.res.mjs";
import * as Convex_users from "./bindings/generated/Convex_users.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function App(props) {
  let match = React.useState(() => {});
  let setCurrentUserId = match[1];
  let currentUserId = match[0];
  let match$1 = React.useState(() => {});
  let setCurrentRoomId = match$1[1];
  let currentRoomId = match$1[0];
  let match$2 = React.useState(() => "");
  let setUserName = match$2[1];
  let userName = match$2[0];
  let match$3 = React.useState(() => "");
  let setUserEmail = match$3[1];
  let userEmail = match$3[0];
  let match$4 = React.useState(() => "General Chat");
  let setRoomName = match$4[1];
  let roomName = match$4[0];
  let createUser = Convex_users.Mutation_create.use();
  let createRoom = Convex_rooms.Mutation_create.use();
  let joinRoom = Convex_rooms.Mutation_join.use();
  let users = Convex_users.Query_list.use(10);
  let rooms = Convex_rooms.Query_list.use(undefined);
  let handleCreateUser = async param => {
    if (userName === "" || userEmail === "") {
      return;
    }
    try {
      let userId = await createUser({
        name: userName,
        email: userEmail,
        avatar: undefined
      });
      setCurrentUserId(param => userId);
      console.log("Created user:", userId);
      return;
    } catch (raw_err) {
      let err = Primitive_exceptions.internalToException(raw_err);
      if (err.RE_EXN_ID === Stdlib_Exn.$$Error) {
        console.error("Failed to create user:", err._1);
        return;
      }
      throw err;
    }
  };
  let handleCreateRoom = async param => {
    if (currentUserId !== undefined) {
      try {
        let roomId = await createRoom({
          name: roomName,
          description: "A place to chat",
          type: "public",
          userId: currentUserId
        });
        setCurrentRoomId(param => roomId);
        console.log("Created room:", roomId);
        return;
      } catch (raw_err) {
        let err = Primitive_exceptions.internalToException(raw_err);
        if (err.RE_EXN_ID === Stdlib_Exn.$$Error) {
          console.error("Failed to create room:", err._1);
          return;
        }
        throw err;
      }
    } else {
      console.error("No user selected");
      return;
    }
  };
  let handleJoinRoom = async roomId => {
    if (currentUserId !== undefined) {
      try {
        await joinRoom({
          roomId: roomId,
          userId: currentUserId
        });
        setCurrentRoomId(param => roomId);
        console.log("Joined room:", roomId);
        return;
      } catch (raw_err) {
        let err = Primitive_exceptions.internalToException(raw_err);
        if (err.RE_EXN_ID === Stdlib_Exn.$$Error) {
          console.error("Failed to join room:", err._1);
          return;
        }
        throw err;
      }
    } else {
      console.error("No user selected");
      return;
    }
  };
  let tmp;
  let exit = 0;
  if (currentUserId !== undefined && currentRoomId !== undefined) {
    tmp = JsxRuntime.jsx(ChatRoom.make, {
      roomId: currentRoomId,
      userId: currentUserId
    });
  } else {
    exit = 1;
  }
  if (exit === 1) {
    tmp = JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("h1", {
          children: "ReScript + Convex Chat Demo",
          className: "text-3xl font-bold mb-8"
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("h2", {
              children: "Step 1: Create or Select User",
              className: "text-xl font-semibold mb-4"
            }),
            currentUserId !== undefined ? JsxRuntime.jsx("div", {
                children: `✓ User selected: ` + currentUserId,
                className: "text-green-600"
              }) : JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("input", {
                        className: "flex-1 px-3 py-2 border rounded",
                        placeholder: "Your name",
                        type: "text",
                        value: userName,
                        onChange: e => {
                          console.log("e", e);
                          setUserName(param => e.target.value);
                        }
                      }),
                      JsxRuntime.jsx("input", {
                        className: "flex-1 px-3 py-2 border rounded",
                        placeholder: "Your email",
                        type: "email",
                        value: userEmail,
                        onChange: e => setUserEmail(param => e.target.value)
                      }),
                      JsxRuntime.jsx("button", {
                        children: "Create User",
                        className: "px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 disabled:opacity-50",
                        disabled: userName === "" || userEmail === "",
                        onClick: param => {
                          handleCreateUser();
                        }
                      })
                    ],
                    className: "flex gap-2 mb-4"
                  }),
                  users !== undefined && users.length !== 0 ? JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("p", {
                          children: "Or select existing user:",
                          className: "text-sm text-gray-600 mb-2"
                        }),
                        JsxRuntime.jsx("div", {
                          children: users.map(user => JsxRuntime.jsxs("button", {
                            children: [
                              JsxRuntime.jsx("div", {
                                children: user.name,
                                className: "font-semibold"
                              }),
                              JsxRuntime.jsx("div", {
                                children: user.email,
                                className: "text-sm text-gray-600"
                              })
                            ],
                            className: "p-2 text-left border rounded hover:bg-gray-50",
                            onClick: param => setCurrentUserId(param => user._id)
                          }, user._id)),
                          className: "grid grid-cols-2 gap-2"
                        })
                      ]
                    }) : null
                ]
              })
          ],
          className: "mb-8 p-6 bg-white rounded-lg shadow"
        }),
        currentUserId !== undefined ? JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("h2", {
                children: "Step 2: Create or Join Room",
                className: "text-xl font-semibold mb-4"
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("input", {
                    className: "flex-1 px-3 py-2 border rounded",
                    placeholder: "Room name",
                    type: "text",
                    value: roomName,
                    onChange: e => setRoomName(param => e.target.value)
                  }),
                  JsxRuntime.jsx("button", {
                    children: "Create Room",
                    className: "px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600 disabled:opacity-50",
                    disabled: roomName === "",
                    onClick: param => {
                      handleCreateRoom();
                    }
                  })
                ],
                className: "flex gap-2 mb-4"
              }),
              rooms !== undefined ? (
                  rooms.length !== 0 ? JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("p", {
                          children: "Or join existing room:",
                          className: "text-sm text-gray-600 mb-2"
                        }),
                        JsxRuntime.jsx("div", {
                          children: rooms.map(room => {
                            let desc = room.description;
                            let match = room.type;
                            return JsxRuntime.jsxs("button", {
                              children: [
                                JsxRuntime.jsx("div", {
                                  children: room.name,
                                  className: "font-semibold"
                                }),
                                desc !== undefined ? JsxRuntime.jsx("div", {
                                    children: desc,
                                    className: "text-sm text-gray-600"
                                  }) : null,
                                JsxRuntime.jsx("div", {
                                  children: `Type: ` + (
                                    match === "private" ? "Private" : (
                                        match === "direct" ? "Direct" : "Public"
                                      )
                                  ),
                                  className: "text-xs text-gray-500 mt-1"
                                })
                              ],
                              className: "p-3 text-left border rounded hover:bg-gray-50",
                              onClick: param => {
                                handleJoinRoom(room._id);
                              }
                            }, room._id);
                          }),
                          className: "grid grid-cols-2 gap-2"
                        })
                      ]
                    }) : JsxRuntime.jsx("div", {
                      children: "No rooms available. Create one!",
                      className: "text-gray-500"
                    })
                ) : null
            ],
            className: "p-6 bg-white rounded-lg shadow"
          }) : null
      ],
      className: "flex-1 p-8 max-w-4xl mx-auto"
    });
  }
  return JsxRuntime.jsx("div", {
    children: tmp,
    className: "h-screen flex"
  });
}

let make = App;

export {
  make,
}
/* react Not a pure module */
