// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.res.mjs";
import * as React from "react";
import * as React$1 from "convex/react";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

import './index.css'
;

let url = import.meta.env.VITE_CONVEX_URL;

let client = url !== undefined ? (console.log("Convex URL:", url), new React$1.ConvexReactClient(url)) : new React$1.ConvexReactClient("https://your-project.convex.cloud");

let domElement = document.querySelector("#root");

if (!(domElement == null)) {
  Client.createRoot(domElement).render(JsxRuntime.jsx(React.StrictMode, {
    children: JsxRuntime.jsx(React$1.ConvexProvider, {
      client: client,
      children: JsxRuntime.jsx(App.make, {})
    })
  }));
}

export {
  client,
}
/*  Not a pure module */
