// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Button from "./button";

let make = Button.Button;

let Button$1 = {
  make: make
};

export {
  Button$1 as Button,
}
/* make Not a pure module */
